// <auto-generated />
using System;
using DiscordBot.Service.RecordKeeping.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBot.Service.RecordKeeping.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104174654_AddValueComparerForFeatures")]
    partial class AddValueComparerForFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<float?>("DurationSecs")
                        .HasColumnType("real");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoiceMessage")
                        .HasColumnType("bit");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Waveform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EntityDiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("PerformedById");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ArchiveTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("AvailableTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DefaultAutoArchiveDuration")
                        .HasColumnType("int");

                    b.Property<string>("DefaultReactionEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultSortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultThreadRateLimitPerUser")
                        .HasColumnType("int");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ParentId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("PermissionOverwrites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("RateLimitPerUser")
                        .HasColumnType("int");

                    b.Property<int>("SlowModeInterval")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordEmbed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Color")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Embeds");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AfkChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("AfkTimeout")
                        .HasColumnType("int");

                    b.Property<int?>("ApproximateMemberCount")
                        .HasColumnType("int");

                    b.Property<int?>("ApproximatePresenceCount")
                        .HasColumnType("int");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DefaultMessageNotifications")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ExplicitContentFilter")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("bit");

                    b.Property<long?>("JoinedAt")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<int?>("MaxVideoChannelUsers")
                        .HasColumnType("int");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("PreferredLocale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PremiumSubscriptionCount")
                        .HasColumnType("int");

                    b.Property<int>("PremiumTier")
                        .HasColumnType("int");

                    b.Property<decimal?>("PublicUpdatesChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("RulesChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("SystemChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("VanityUrlCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerificationLevel")
                        .HasColumnType("int");

                    b.Property<bool>("WidgetEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuildUserRole", b =>
                {
                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("bigint");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "UserId", "RoleId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("GuildUserRoles");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<int?>("InviterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TargetApplicationId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("TargetType")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetUserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("InviterId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApplicationId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long?>("EditedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<decimal?>("InteractionId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTTS")
                        .HasColumnType("bit");

                    b.Property<string>("MentionedChannelIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MentionedEveryone")
                        .HasColumnType("bit");

                    b.Property<string>("MentionedRoleIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentionedUserIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ReferencedMessageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThreadId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WebhookId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("ReferencedMessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessageSticker", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("StickerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "StickerId");

                    b.HasIndex("StickerId");

                    b.ToTable("MessageStickers");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordPresenceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("ActivityUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomStatusEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("PresenceLogs");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("EmojiId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("EmojiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBurst")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomEmoji")
                        .HasColumnType("bit");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RemovedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId", "EmojiName", "EmojiId")
                        .IsUnique()
                        .HasFilter("[EmojiId] IS NOT NULL");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHoisted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMentionable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnicodeEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordScheduledEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("EntityMetadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("int");

                    b.Property<long?>("ScheduledEndTime")
                        .HasColumnType("bigint");

                    b.Property<long>("ScheduledStartTime")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("ScheduledEvents");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordSticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("FormatType")
                        .HasColumnType("int");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PackId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("SortValue")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccentColor")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GlobalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWebhook")
                        .HasColumnType("bit");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PremiumType")
                        .HasColumnType("int");

                    b.Property<int>("PublicFlags")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("Username", "Discriminator")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUserBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BannedAt")
                        .HasColumnType("bigint");

                    b.Property<int?>("BannedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UnbannedAt")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnbannedById")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BannedById");

                    b.HasIndex("GuildId");

                    b.HasIndex("UnbannedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserBans");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUserNickname", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNicknames");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordVoiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelfDeafened")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelfMuted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServerDeafened")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServerMuted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStreaming")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVideoEnabled")
                        .HasColumnType("bit");

                    b.Property<long>("JoinedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("LeftAt")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RequestToSpeakTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("VoiceSessions");
                });

            modelBuilder.Entity("DiscordChannelDiscordUser", b =>
                {
                    b.Property<int>("ChannelsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ChannelsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("DiscordUserChannels", (string)null);
                });

            modelBuilder.Entity("DiscordGuildDiscordUser", b =>
                {
                    b.Property<int>("GuildsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("GuildsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("DiscordUserGuilds", (string)null);
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordAttachment", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordAuditLog", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("AuditLogs")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "PerformedBy")
                        .WithMany("AuditLogsPerformed")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", "Category")
                        .WithMany("ChildChannels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordEmbed", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", "Message")
                        .WithMany("Embeds")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuildUserRole", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Guild");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordInvite", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", "Channel")
                        .WithMany("Invites")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "Inviter")
                        .WithMany("InvitesCreated")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Guild");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Messages")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", "ReferencedMessage")
                        .WithMany("ReferencedByMessages")
                        .HasForeignKey("ReferencedMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Channel");

                    b.Navigation("Guild");

                    b.Navigation("ReferencedMessage");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessageSticker", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordSticker", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Sticker");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordPresenceLog", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("PresenceLogs")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("PresenceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordReaction", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordRole", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordScheduledEvent", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", "Channel")
                        .WithMany("ScheduledEvents")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "Creator")
                        .WithMany("ScheduledEventsCreated")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("ScheduledEvents")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Creator");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordSticker", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Stickers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("StickersCreated")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUserBan", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "BannedBy")
                        .WithMany("BansIssued")
                        .HasForeignKey("BannedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Bans")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "UnbannedBy")
                        .WithMany()
                        .HasForeignKey("UnbannedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedBy");

                    b.Navigation("Guild");

                    b.Navigation("UnbannedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUserNickname", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Nicknames")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("Nicknames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordVoiceSession", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", "Channel")
                        .WithMany("VoiceSessions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("VoiceSessions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", "User")
                        .WithMany("VoiceSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordChannelDiscordUser", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordGuildDiscordUser", b =>
                {
                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", null)
                        .WithMany()
                        .HasForeignKey("GuildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordChannel", b =>
                {
                    b.Navigation("ChildChannels");

                    b.Navigation("Invites");

                    b.Navigation("Messages");

                    b.Navigation("ScheduledEvents");

                    b.Navigation("VoiceSessions");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordGuild", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bans");

                    b.Navigation("Channels");

                    b.Navigation("Invites");

                    b.Navigation("Messages");

                    b.Navigation("Nicknames");

                    b.Navigation("PresenceLogs");

                    b.Navigation("Roles");

                    b.Navigation("ScheduledEvents");

                    b.Navigation("Stickers");

                    b.Navigation("VoiceSessions");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Embeds");

                    b.Navigation("Reactions");

                    b.Navigation("ReferencedByMessages");
                });

            modelBuilder.Entity("DiscordBot.Service.RecordKeeping.Core.Domain.Entities.DiscordUser", b =>
                {
                    b.Navigation("AuditLogsPerformed");

                    b.Navigation("Bans");

                    b.Navigation("BansIssued");

                    b.Navigation("InvitesCreated");

                    b.Navigation("Messages");

                    b.Navigation("Nicknames");

                    b.Navigation("PresenceLogs");

                    b.Navigation("Reactions");

                    b.Navigation("ScheduledEventsCreated");

                    b.Navigation("StickersCreated");

                    b.Navigation("VoiceSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
