// <auto-generated />
using DiscordBot.Infrastructure.Data;
using DiscordBot.Infrastructure.Data.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
